/**
 * @typedef {object} Meme
 * @property {string} id
 * @property {string} text0
 * @property {string} text1
 */


/**
 * Offset in weeks
 * @type {number}
 */
window.memesOffset = 16

/**
 * Index used as week number, respecting memesOffset
 * @type {Meme[]} memes
 */
window.memes = [
    {
        id: "112126428",
        default: "Distracted Boyfriend",
        descr: "distracted bf, guy checking out another girl, man looking at other woman, jealous girlfriend, guy looking back, cheater temptation, wandering eyes, disloyal boyfriend",
        text0: 'Not the chairman',
        text1: '{{name}}',
    },
    {
        id: "181913649",
        default: "Drake Hotline Bling",
        descr: "drakeposting, drakepost, drake hotline approves, drake no yes, drake like dislike, drake faces",
        text0: 'Please remove the amateurs',
        text1: '{{name}} is your chairman',
    },
    {
        id: "87743020",
        default: "Two Buttons",
        descr: "2 red buttons, choice button, which button, daily struggle, hard choice to make",
        text0: '{{name}}',
        text1: '{{name}}',
    },
    {
        id: "438680",
        default: "Batman Slapping Robin",
        descr: "",
        text0: 'Maybe Rineke this time?',
        text1: 'NO! it\'s your turn {{name}}.',
    },
    {
        id: "61579",
        default: "One Does Not Simply",
        descr: "one does not simply walk into morder, lord of the rings boromir",
        text0: 'One does not simple',
        text1: 'man the chair',
    },
    {
        id: "102156234",
        default: "Mocking Spongebob",
        descr: "spongebob mock, spongebob chicken, retarded spongebob, sarcastic spongebob, spongebob stupid, spongebob derp, spongebob bird, spongebob mocking face",
        text0: 'He lives in a pineapple under the sea',
        text1: '{{name}}bob chairman!',
    },
    {
        id: "101470",
        default: "Ancient Aliens",
        descr: "Giorgio Tsoukalos, History Channel Guy",
        text0: '',
        text1: 'I got this',
    },
    {
        id: "4087833",
        default: "Waiting Skeleton",
        descr: "skeleton waiting on bench in the park",
        text0: '',
        text1: '{{name}} waiting for his round at chairman',
    },
    {
        id: "89370399",
        default: "Roll Safe Think About It",
        descr: "thinking black guy, black guy pointing at his head, can't blank if you don't blank, smart black dude, guy tapping head",
        text0: 'I have a chair and I am a man',
        text1: 'I could be chairman, think about it',
    },
    {
        id: "217743513",
        default: "UNO Draw 25 Cards",
        descr: "do something you don’t like or draw 25 cards, uno dilemma, uno or draw 25, draw 25",
        text0: 'Be chairman',
        text1: '{{name}}',
    },

    {
        id: "55311130",
        default: "This Is Fine",
        descr: "this is fine dog, dog house fire, dog in burning house, house on fire",
        text0: '{{name}} the chairdog',
        text1: '',
    },
    {
        id: "195515965",
        default: "Clown Applying Makeup",
        descr: "putting on clown makeup, clown face, clown paint, becoming a clown",
        text0: '{{name}} started early this morning',
        text1: '',
    },
    {
        id: "163573",
        default: "Imagination Spongebob",
        descr: "spongebob rainbow, nobody cares",
        text0: 'Let\'s wait for the',
        text1: 'Sparkles!',
    },
    {
        id: "766986",
        default: "Aaaaand Its Gone",
        descr: "and it's gone, south park banker guy",
        text0: '',
        text1: 'thanks for the GFA. And... It\'s gone',
    },
    {
        id: "21604248",
        default: "Mugatu So Hot Right Now",
        descr: "Mugatu from Zoolander, Will Farrell",
        text1: 'Exciting!',
    },
    {
        id: "100955",
        default: "Confession Bear",
        descr: "",
        text0: '',
        text1: 'Again?',
    },
    {
        id: "460541",
        default: "Jack Sparrow Being Chased",
        descr: "pirates of the caribbean",
        text0: 'No i\'m not!',
        text1: 'Time to MOVE',
    },
    {
        id: "718432",
        default: "Back In My Day",
        descr: "grumpy old man pointing",
        text0: 'No i\'m not!',
        text1: 'Time to MOVE',
    },
    {
        id: "124212",
        default: "Say That Again I Dare You",
        descr: "Samuel L Jackson, pulp fiction",
        text0: 'So, anyone who didn\'t',
        text1: 'finish there tickets?',
    },
    {
        id: "13757816",
        default: "Awkward Moment Sealion",
        descr: "awkward seal, uncomfortable situation sealion, heavy breathing sealion",
        text0: 'Did you have to',
        text1: 'make this awkward?',
    },
    {
        id: "91538330",
        default: "X, X Everywhere",
        descr: "woody and buzz lightyear pointing, toy story, dicks everywhere, toystory everywhere",
        text0: 'We are going to do it',
        text1: 'completely different'
    },
    {
        id: "61520",
        default: "Futurama Fry",
        descr: "Not sure if X or Y, Skeptical Fry",
        text0: '',
        text1: "maybe this will go well"
    },
    {
        id: "119139145",
        default: "Blank Nut Button",
        descr: "blank blue button, smash button, press button, button slam",
		text0: '{{name}}',
		text1: 'Deploy button',
    },
    {
        id: "97984",
        default: "Disaster Girl",
        descr: "",
		text0: 'Gap scenario',
        text1: '',
    },
    {
        id: "5496396",
        default: "Leonardo Dicaprio Cheers",
        descr: "The Great Gatsby party with Jay Gatsby, gatsby toast",
        text0: '',
		text1: 'Sure no problem',
    },
    {
        id: "123999232",
        default: "The Scroll Of Truth",
        descr: "I've finally found it... after 15 years, nyehhh",
		text0: '{{name}} is chairman for life',
        text1: '',
    },
    // {
    //     id: "124055727",
    //     default: "Y'all Got Any More Of That",
    //     descr: "Tyrone Biggums, Dave Chappelle, Chappelles Show, yall got any more of that stuff, powder lips neck scratch",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "222403160",
    //     default: "Bernie I Am Once Again Asking For Your Support",
    //     descr: "bernie sanders commercial, bernie sanders 2020 campaign, asking for your financial support, once again bernie",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "247375501",
    //     default: "Buff Doge vs. Cheems",
    //     descr: "swole doge vs cheems, strong doge weak doge, big doge small doge, then vs. now, buff doge vs. crying cheems",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "27813981",
    //     default: "Hide the Pain Harold",
    //     descr: "sad life harold, maurice",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "28251713",
    //     default: "Oprah You Get A",
    //     descr: "oprah giveway, oprah winfrey, oprah you get a car, everyone gets a car, you get an oprah, oprah excited",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "178591752",
    //     default: "Tuxedo Winnie The Pooh",
    //     descr: "winnie the poo, winnie the pooh drake style, classy pooh bear, tuxedo pooh, winnie the pooh elegant, winnie pooh, winnie the pooh tux, fancy pooh",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "61527",
    //     default: "Y U No",
    //     descr: "",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "134797956",
    //     default: "American Chopper Argument",
    //     descr: "orange county choppers fight, american chopper hot take",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "101288",
    //     default: "Third World Skeptical Kid",
    //     descr: "African skeptical child",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "6235864",
    //     default: "Finding Neverland",
    //     descr: "Johnny Depp And Little Kid Crying",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "131940431",
    //     default: "Gru's Plan",
    //     descr: "Grus evil plan, Despicable Me diabolical plan, Gru's diabolical plan, gru 4 panel",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "563423",
    //     default: "That Would Be Great",
    //     descr: "Bill Lumbergh, office space, yea that'd be great",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "61546",
    //     default: "Brace Yourselves X is Coming",
    //     descr: "imminent ned from game of thrones, brace yourselves winter is coming, brace yourself",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "226297822",
    //     default: "Panik Kalm Panik",
    //     descr: "panic calm panic, meme man wurds",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "61582",
    //     default: "Creepy Condescending Wonka",
    //     descr: "willy wonka stare, sarcastic wonka, tell me more about X, tell me again, gene wilder",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "148909805",
    //     default: "Monkey Puppet",
    //     descr: "monkey looking away, monkey puppet avoids eye contact, hiding in plain sight, awkward look monkey",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "61533",
    //     default: "X All The Y",
    //     descr: "all the things",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "61556",
    //     default: "Grandma Finds The Internet",
    //     descr: "",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "405658",
    //     default: "Grumpy Cat",
    //     descr: "",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "91545132",
    //     default: "Trump Bill Signing",
    //     descr: "executive order trump",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "14371066",
    //     default: "Star Wars Yoda",
    //     descr: "master yoda",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "16464531",
    //     default: "But That's None Of My Business",
    //     descr: "Kermit the frog, kermit drinking lipton iced tea",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "101511",
    //     default: "Don't You Squidward",
    //     descr: "spongebob grinning, spongebob smirk face, smug spongebob",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "135256802",
    //     default: "Epic Handshake",
    //     descr: "arm wrestling, holding hands, grasping hands, epic hand shake, black white arms agreement",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "1509839",
    //     default: "Captain Picard Facepalm",
    //     descr: "star trek face palm",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "175540452",
    //     default: "Unsettled Tom",
    //     descr: "tom face, concerned tom, tom and jerry, disgusted tom, surprised tom, tom staring down",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "101287",
    //     default: "Third World Success Kid",
    //     descr: "happy african child, african kids dancing",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "84341851",
    //     default: "Evil Kermit",
    //     descr: "kermit me to me, kermit inner me, sith kermit, kermit dark side",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "235589",
    //     default: "Evil Toddler",
    //     descr: "evil baby",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "61544",
    //     default: "Success Kid",
    //     descr: "Motivation Baby, Motivation Kid, Success Baby",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "100947",
    //     default: "Matrix Morpheus",
    //     descr: "what if I told you",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "14230520",
    //     default: "Black Girl Wat",
    //     descr: "confused black girl, black girl with hand out, seriously black girl",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "252600902",
    //     default: "Always Has Been",
    //     descr: "wait it's all just ohio, two astronauts betrayal, astronaut gun, astronaut lie, astronaut discovers conspiracy theory, always have been, it always was",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "135678846",
    //     default: "Who Killed Hannibal",
    //     descr: "Eric Andre shooting Hannibal Buress, why would they do this",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "80707627",
    //     default: "Sad Pablo Escobar",
    //     descr: "pablo escobar waiting, man waiting, waiting man, lonely man, narcos waiting, narcos bored, narcos alone",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "61516",
    //     default: "Philosoraptor",
    //     descr: "green dinosaur, dinosaur wondering",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "245898",
    //     default: "Picard Wtf",
    //     descr: "captain jean-luc picard star trek, annoyed picard, why the fuck would you",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "161865971",
    //     default: "Marked Safe From",
    //     descr: "facebook marked safe, marked safe flag, marked safe today, facebook safe from",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "196652226",
    //     default: "Spongebob Ight Imma Head Out",
    //     descr: "Ight Imma Head Out, aight imma head out, spongebob aight, alright I'm out, spongebob getting out of chair",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "101440",
    //     default: "10 Guy",
    //     descr: "Really High Guy, Stoner Stanley, Brainwashed Bob, stoned guy, ten guy",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "132769734",
    //     default: "Hard To Swallow Pills",
    //     descr: "hard pills to swallow",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "922147",
    //     default: "Laughing Men In Suits",
    //     descr: "Men laughing, And then I said, And then I told them, rich men laughing",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "180190441",
    //     default: "They're The Same Picture",
    //     descr: "it's the same picture, corporate needs you to find the differences between this picture and this picture, pam from the office, office same picture, spot the difference",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "3218037",
    //     default: "This Is Where I'd Put My Trophy If I Had One",
    //     descr: "",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "61580",
    //     default: "Too Damn High",
    //     descr: "The rent is too damn high",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "40945639",
    //     default: "Dr Evil Laser",
    //     descr: "Dr. Evil quotation marks, Dr Evil Air Quotes",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "259680",
    //     default: "Am I The Only One Around Here",
    //     descr: "Angry Walter from The Big Lebowski",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "101910402",
    //     default: "Who Would Win?",
    //     descr: "",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "101716",
    //     default: "Yo Dawg Heard You",
    //     descr: "Xzibit, Yo dawg we heard you like Y so we put some X in your X so you can Y while you Y",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "109765",
    //     default: "I'll Just Wait Here",
    //     descr: "waiting skeleton",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "9440985",
    //     default: "Face You Make Robert Downey Jr",
    //     descr: "",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "61581",
    //     default: "Put It Somewhere Else Patrick",
    //     descr: "patrick from spongebob",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "110163934",
    //     default: "I Bet He's Thinking About Other Women",
    //     descr: "i bet he's thinking of other woman, i bet he's thinking about other girls, couple in bed, i wonder what he's thinking, guy thinking in bed",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
    // {
    //     id: "56225174",
    //     default: "Be Like Bill",
    //     descr: "bill the stick figure with a hat",
	// 	text0: 'text0',
	// 	text1: 'text1',
    // },
]
