/**
 * Index used as week number, starting week 0 2021
 * @type {string[]}
 */
window.names = [
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "Lamberto",
    "Festy",
    "IP sprint",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Rahul",
    "Rahul",
    "Phani",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
    "Inam",
    "Marcel",
    "Ramon",
    "Amol",
    "Ganesh",
    "Phani",
    "Rahul",
    "The Sherminator",
    "Lamberto",
    "Festy",
]
